insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('2', 'Tudor Oprea', 'OPR', '2020FF', '6DHB3Z3', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('3', 'Arpad Kelemen', 'KLMN', '2020FF', '8KNNV0P', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('4', 'Daniel Marius Rosioru', 'RSR', '2020FF', '1YMD03M', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('5', 'Elisei Miron', 'MRN', '2020FF', '4XKWCD3', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('6', 'Lucian Logigan', 'LGGN', '33EE00', '8WHMYSC', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('7', 'Eduard Michael Grosu', 'GRS', '33EE00', '4XHNW3C', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('8', 'Ionut Sdraila', 'SDRL', '33EE00', '9RH7SYX', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('9', 'Robert Kovacs', 'KVCS', '33EE00', '3TNSBVE', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('10', 'Mircea Robert Gustav', 'ROBK', 'FFEE00', '4XHM26F', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('11', 'Stefan Constantin', null, '33EE00', '1MMA45X', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('12', 'Marian Frunzeanu', 'FRNZ', '33EE00', '3DHSXX6', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('13', 'Alex Ciocan', null, '2020FF', '6SHME19', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('14', 'Gabriel Tintea', 'TNT', '33EE00', '1RHVCMG', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('15', 'Gheduzzi Ulisse', 'GDZZ', 'FFEE00', '8EHETXR', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('16', 'Francisc Sarosi', 'SRS', 'FFEE00', '3DN2MVS', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('17', 'Marius Ionascu', 'Maus', 'FFEE00', '4AMK3KH', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('18', 'Stefan Morcov', 'MRCV', 'FFEE00', '1FM5RYT', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('19', 'Cristian Losonczi', 'LSNC', '33EE00', '3YHM1XG', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('20', 'Fabian Gandila', 'GNDL', '33EE00', '4XNGER9', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('21', 'Attila Madaras', 'MDRS', '33EE00', '4FMK4F2', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('22', 'Alexandru Grozea', 'GRZ', '33EE00', '8WNRSW4', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('23', 'Vlad Dinu', 'DNV', '33EE00', '3TH8K32', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('24', 'Adrian Dumitru', 'DMTR', '33EE00', '6DNTY93', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('25', 'Gabriel Daitoiu', 'DTG', '2020FF', '3ZK66EF', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('26', 'Sergiu Paraschivu', null, '33EE00', '9RHGEHW', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('27', 'Marian Marin', null, '2020FF', '1RMPVXG', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('28', 'Andrei Cristian Pop', null, '2020FF', '3YNFS48', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('29', 'Filip - Ilie Grigorescu', null, '2020FF', '1AMZCBN', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('30', 'Dorin Dîrnescu', null, '33EE00', '1KN3SD9', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('31', 'Vlad Sabau', null, '33EE00', '4NMWAN3', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('32', 'Andrei Bobic', null, '2020FF', '6SN238A', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('33', 'Christian Rakosy', null, '2020FF', '1MMF2N3', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('34', 'Alexandru Stancu', null, '2020FF', '4XNGPXP', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('35', 'Sebastian Luca', null, '33EE00', '8WKW5YM', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('36', 'Nicolae Andreica', null, '2020FF', '8KH0FCY', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('37', 'Alexandru Stancu', null, '33EE00', '3GH5X9C', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('38', 'Robert Sofronie', null, '33EE00', '1AHNX2R', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('39', 'Calin-Alexandru Serban', null, '33EE00', '4NK9AAP', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('40', 'Emese Fodor', null, 'FF4400', '8WHNK31', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('41', 'Zsuzsa Gyurka', null, 'FF4400', '4XNNPBB', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('42', 'Anca Burlacu', null, 'FF4400', '4FKNZ8P', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('43', 'Andreea Nicoleta Anghelus', null, 'FF4400', '8WMTYTE', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('44', 'Beata Adrienne Piringer', null, 'FF4400', '8ZN2T4Y', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('45', 'Irina Dumitru', null, 'FF4400', '3SNFSYM', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('46', 'Monica Cojocaru', null, 'FF4400', '2NM3467', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('47', 'Roxana Lupu', null, 'FF4400', '8MHTCWN', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('48', 'Vanessa Plumbota', null, 'FF4400', '8KNM33H', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('50', 'Fabio Gattoni', null, '2020FF', '2XMM3R2', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('51', 'Andrei Racasan', null, '33EE00', '8GH4CW7', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('52', 'Ionel Duta', null, '33EE00', '6ENV5BB', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('53', 'Mihai Rusu', null, '33EE00', '1MHSX82', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('54', 'Popovici Georgian', null, '33EE00', '8WMNKAR', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('55', 'Adrian Nitu', null, '33EE00', '8ZKCFTB', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('56', 'Vlad-Nicolae Dobre', null, '33EE00', '1RK6M3H', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('57', 'Horatiu Campian', null, '2020FF', '1RHAR5Z', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('58', 'Istvan Csergedi', null, '2020FF', '6EHEPNA', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('59', 'Valeriu Vasile', null, '33EE00', '1MM877E', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('60', 'Tudor Radu', null, '33EE00', '6SNNV5Z', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('61', 'Angelos Georgiadis', null, '33EE00', '8KKDSNC', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('62', 'Antonio Vieru', null, '2020FF', '4XH5ZMZ', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('63', 'Bogdan Vlad', null, '33EE00', '6SHT457', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('64', 'Marcian Enache-Poti', null, '2020FF', '3YK9351', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('65', 'Valentin Pasa', null, '2020FF', '6EKDPWG', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('66', 'Bogdan Badoiu', null, '33EE00', '8MMRMXP', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('67', 'Georgios Georgiadis', null, 'FFEE00', '8KKHR1X', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('68', 'Nicusor Poiana', null, '2020FF', '1AHZ43A', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('69', 'Adrian Bobocea', null, '2020FF', '1AHZ9Z8', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('70', 'Adrian Staicu', null, 'FFEE00', '1KHD1FE', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('71', 'Alex Mares', null, '2020FF', '9NHH1FD', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('72', 'Alexandru Mircea', null, '33EE00', '6ENP9VH', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('73', 'Alexandru Oprea', null, '33EE00', '4NHY3S2', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('74', 'Alexandru Lazarescu', null, '2020FF', '8GHFVR3', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('75', 'Alexandru Tiper', null, '2020FF', '3THDBEZ', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('76', 'Alexandru Lazar', null, '2020FF', '4FHKSMK', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('77', 'Alexandru Munteanu', null, '2020FF', '2FNCX5B', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('78', 'Alexandru Draghici', null, '2020FF', '4AMMXR7', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('79', 'Andrei Stanciu', null, '33EE00', '8ZH6D63', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('80', 'Andrei Hodina', null, '33EE00', '6DKTXFZ', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('81', 'Andrei-Cristian Grigore', null, '33EE00', '4FMTEFA', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('82', 'Anton Mihai Paul', null, '2020FF', '1AH9TW6', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('83', 'Aurelian-Mihail Raducanu', null, 'FFEE00', '1RNZRAS', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('84', 'Bogdan Bara', null, '33EE00', '3GKGVPD', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('85', 'Bogdan Cecareanu', null, '2020FF', '4FHCD1N', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('86', 'Bogdan Avramescu', null, '2020FF', '3GHWKT9', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('87', 'Bogdan Tichineata', null, '2020FF', '4YHBZ1M', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('88', 'Bogdan Carciumaru', null, '2020FF', '3DN292G', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('89', 'Bogdan Florin Georgescu', null, '33EE00', '6DNTXY2', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('90', 'Bogdan Ionut Andrei', null, '2020FF', '4NNHSAP', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('91', 'Bogdan-Daniel Vladut', null, '33EE00', '4MMW87V', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('92', 'Bogdan-Mihail Palaghian', null, '2020FF', '3DN33VP', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('93', 'Catalin Constandis', null, '33EE00', '8WNFGAT', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('94', 'Catalin Costea', null, '33EE00', '4NMF1N9', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('95', 'Catalin Toda', null, '2020FF', '4FNT6K5', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('96', 'Catalin Ursachi', null, 'FFEE00', '6SHWBHD', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('97', 'Catalin Muraru', null, 'FFEE00', '4XKGRBD', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('98', 'Cezar Jipa', null, 'FFEE00', '4RK8DBC', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('99', 'Ciprian Dontu', null, '2020FF', '6SKTPEX', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('100', 'Ciprian Rosca', null, '2020FF', '1MKDX34', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('101', 'Cosmin Oprea', null, '33EE00', '1RMANF6', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('102', 'Cristian Constantinescu', null, '33EE00', '2NNSZDV', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('103', 'Cristian Stan', null, '33EE00', '1AK969F', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('104', 'Cristian Dulacioiu', null, '33EE00', '4NH00BF', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('105', 'Cristian Zamfir', null, 'FFEE00', '1MN81VR', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('106', 'Cristian Rene Anghelescu', null, '33EE00', '8SKM3S2', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('107', 'Damien Thiery', null, '2020FF', '1AKB2HB', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('108', 'Dan Leahu', null, '33EE00', '4XH623S', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('109', 'Dan Mecla', null, '2020FF', '1RMPFAW', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('110', 'Dan Muraru', null, 'FFEE00', '6SMRBF2', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('111', 'Dan Adrian Ghetu', null, '2020FF', '3TKHAEX', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('112', 'Dan Mihai Alupoae', null, '33EE00', '6DKXRA2', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('113', 'Daniel Lacusta', null, '33EE00', '4XMFBFW', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('114', 'Daniel Birghilescu', null, '2020FF', '8GN0543', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('115', 'Daniel Geanta', null, '2020FF', '4FHKX7E', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('116', 'Daniel Zarnescu', null, 'FFEE00', '6SKBS9M', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('117', 'Daniel Constantin Rotaru', null, 'FFEE00', '1AHPADP', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('118', 'Dorin Grigoras', null, 'FFEE00', '2MMH0T4', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('119', 'Dragos Ion', null, '2020FF', '1MKWK0V', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('120', 'Emil Cseh', null, 'FFEE00', '2XM4075', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('121', 'Eugen Grosu', null, '2020FF', '8WK6F79', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('122', 'Florin Marza', null, '33EE00', '3YK9CWG', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('123', 'Florin Miu', null, '33EE00', '2KHWNGG', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('124', 'Gabriel Dumitrache', null, '2020FF', '6SNRE6T', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('125', 'Gabriel Vladau', null, '2020FF', '6EHE9ZV', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('126', 'George Dumitrescu', null, '33EE00', '6SN7K84', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('127', 'Guillaume Faudrin', null, '33EE00', '8MHRWC7', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('128', 'Ion Geaca', null, '33EE00', '4ZHVZKF', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('129', 'Ion Cotofana', null, 'FFEE00', '4RM18G8', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('130', 'Ionut Ion', null, '2020FF', '8KHVHWE', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('131', 'Iulian Stanculescu', null, '2020FF', '4FMY823', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('132', 'Leonard Barbu', null, '33EE00', '2XK98NV', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('133', 'Lorand Fabian', null, '2020FF', '4NMFDGX', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('134', 'Lucian Marculescu', null, '2020FF', '8YNEV5R', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('135', 'Lucian Ionel Micu', null, '2020FF', '4AMMA5M', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('136', 'Marin Cristian Ene', null, '33EE00', '1FH564K', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('137', 'Marius Mircea', null, '2020FF', '4FHABN2', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('138', 'Marius Buruianu', null, 'FFEE00', '3SHP38F', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('139', 'Matei Edu', null, '33EE00', '3DH4BW2', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('140', 'Mihai Baloiu', null, '33EE00', '6DNT0VM', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('141', 'Mihai Manda', null, '33EE00', '6SMXDEZ', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('142', 'Mihai Stanoiu', null, '2020FF', '1RMASA6', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('143', 'Mihai Parlea', null, '2020FF', '6DH6TTW', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('144', 'Mihai Draganescu', null, '2020FF', '1AM2HAN', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('145', 'Mihai Gheorghiu', null, '2020FF', '4NN7T4B', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('146', 'Mihai Traian Ion', null, '33EE00', '8SHH7HS', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('147', 'Mihai-Catalin Gogu', null, '2020FF', '8WMMMK5', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('148', 'Mircea Stanculescu', null, '33EE00', '8ZHGWA7', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('149', 'Mircea Ban', null, '2020FF', '4NHVWNY', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('150', 'Mircea - Dorin Marin', null, '2020FF', '8MHRYPT', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('151', 'Mircea Mihai Toma', null, '33EE00', '2MNM26K', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('152', 'Mircea-Alexandru Stefan', null, '33EE00', '1MKDH6H', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('153', 'Nelu Roman', null, '2020FF', '8GMK9M5', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('154', 'Octavian Dragnea', null, '33EE00', '4AMK2XN', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('155', 'Ovidiu Ignat', null, '33EE00', '6EHTTFG', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('156', 'Ovidiu Afrasinei', null, '2020FF', '0XKVTN8', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('157', 'Radu Florea', null, '33EE00', '3GHG0M1', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('158', 'Rares Manea', null, '33EE00', '9XHMS2D', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('159', 'Rares Manolescu', null, '2020FF', '8GM3N7H', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('160', 'Razvan Ilie', null, 'FFEE00', '6SNMA2N', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('161', 'Razvan-Andrei Jipa', null, '33EE00', '6ENV08D', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('162', 'Reginel Darlea', null, 'FFEE00', '4RN9YA8', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('163', 'Sergiu Blidea', null, '33EE00', '8YKECND', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('164', 'Sorin Malea', null, '2020FF', '3TMEK2B', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('165', 'Stefan Uricariu', null, '33EE00', '3TM98XT', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('166', 'Stefan Mihailescu', null, '33EE00', '3YMG47R', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('167', 'Stefan Constantinescu', null, '2020FF', '4XH67EG', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('168', 'Stefan Cristian Farcas', null, '2020FF', '4XN6DZ3', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('169', 'Teodor-Cosmin Ionescu', null, '33EE00', '8GNCTMG', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('170', 'Traian Nuta', null, 'FFEE00', '1AM2HFE', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('171', 'Valentin Nita', null, '33EE00', '3DHP9V6', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('172', 'Valentin Oprisoiu', null, 'FFEE00', '6DMX75R', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('173', 'Victor Rotariu', null, '33EE00', '8EHET2F', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('174', 'Victor Radoi', null, 'FFEE00', '2XNZ7BD', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('175', 'Victor catalin verigeanu', null, 'FFEE00', '8ZHDCHM', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('176', 'Vlad Manolache', null, '33EE00', '6DKT3BD', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('177', 'Istvan Botos', null, '2020FF', '1RHAD05', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('178', null, null, null, '3SM8TFP', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('179', null, null, null, '6EN07BB', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('180', null, null, null, '8KNVW8X', 31);
insert into event_user (trackcode, label, shortname, color, chip, event_fk) values ('49', null, null, null, '3GN26GV', 31);
