insert into event_user(event_fk, trackCode, label) values (3, '1', 'Vlad Galesanu');
insert into event_user(event_fk, trackCode, label) values (3, '2', 'Mihai Vilnoiu');
insert into event_user(event_fk, trackCode, label) values (3, '3', 'Bogdan Alecu');
insert into event_user(event_fk, trackCode, label) values (3, '4', 'Leonard Barbu');
insert into event_user(event_fk, trackCode, label) values (3, '5', 'Vasile Borta');
insert into event_user(event_fk, trackCode, label) values (3, '6', 'Francesco Capuzzo');
insert into event_user(event_fk, trackCode, label) values (3, '7', 'Daniel Dascal');
insert into event_user(event_fk, trackCode, label) values (3, '8', 'Adrian Draghici');
insert into event_user(event_fk, trackCode, label) values (3, '9', 'Maria-Diana Elisei');
insert into event_user(event_fk, trackCode, label) values (3, '10', 'Alina Ene');
insert into event_user(event_fk, trackCode, label) values (3, '11', 'Alexandru Hoandra');
insert into event_user(event_fk, trackCode, label) values (3, '12', 'Arpad Horvath');
insert into event_user(event_fk, trackCode, label) values (3, '13', 'Cezar Jipa');
insert into event_user(event_fk, trackCode, label) values (3, '14', 'Dragos Jula');
insert into event_user(event_fk, trackCode, label) values (3, '15', 'Marian Marin');
insert into event_user(event_fk, trackCode, label) values (3, '16', 'Claudiu Moldovan');
insert into event_user(event_fk, trackCode, label) values (3, '17', 'Alexandru Munteanu');
insert into event_user(event_fk, trackCode, label) values (3, '18', 'Marius Pescaru');
insert into event_user(event_fk, trackCode, label) values (3, '19', 'Egon Pommersheim');
insert into event_user(event_fk, trackCode, label) values (3, '20', 'Constantin Popa');
insert into event_user(event_fk, trackCode, label) values (3, '21', 'Alexandru Popiel');
insert into event_user(event_fk, trackCode, label) values (3, '22', 'Alexandru Pulpa');
insert into event_user(event_fk, trackCode, label) values (3, '23', 'Darius Radu');
insert into event_user(event_fk, trackCode, label) values (3, '24', 'Aurelian-Mihail Raducanu');
insert into event_user(event_fk, trackCode, label) values (3, '25', 'Francisc Sarosi');
insert into event_user(event_fk, trackCode, label) values (3, '26', 'Claudiu Marian Staicu');
insert into event_user(event_fk, trackCode, label) values (3, '27', 'Sorin Suciu');
insert into event_user(event_fk, trackCode, label) values (3, '28', 'Doina Titei');
insert into event_user(event_fk, trackCode, label) values (3, '29', 'Oana Mihaela Trif');
insert into event_user(event_fk, trackCode, label) values (3, '30', 'Ioan Matanie');
insert into event_user(event_fk, trackCode, label) values (3, '31', 'Octavian Dobrin');
insert into event_user(event_fk, trackCode, label) values (3, '32', 'Doru Daniel Calin');
insert into event_user(event_fk, trackCode, label) values (3, '33', 'Cristian Iordan');
insert into event_user(event_fk, trackCode, label) values (3, '34', 'Jan Glas');
insert into event_user(event_fk, trackCode, label) values (3, '35', 'Csaba Kerekes');
insert into event_user(event_fk, trackCode, label) values (3, '36', 'Istvan Kerekes');
insert into event_user(event_fk, trackCode, label) values (3, '37', 'Bogdan Dumitru');
insert into event_user(event_fk, trackCode, label) values (3, '38', 'Ciprian Rosca');
insert into event_user(event_fk, trackCode, label) values (3, '39', 'Aurelian Costache');
insert into event_user(event_fk, trackCode, label) values (3, '40', 'Dorin Grigoras');
insert into event_user(event_fk, trackCode, label) values (3, '41', 'Radu Blaga');
insert into event_user(event_fk, trackCode, label) values (3, '42', 'Ionut Matanie');
insert into event_user(event_fk, trackCode, label) values (3, '43', 'Ionut Ion');
insert into event_user(event_fk, trackCode, label) values (3, '44', 'Mihai Stanoiu');
insert into event_user(event_fk, trackCode, label) values (3, '45', 'Mihai Mincu');
insert into event_user(event_fk, trackCode, label) values (3, '46', 'Teodor-Cristian Ionescu');
insert into event_user(event_fk, trackCode, label) values (3, '47', 'Dan Mazilu');
insert into event_user(event_fk, trackCode, label) values (3, '48', 'Valeriu Coman');
insert into event_user(event_fk, trackCode, label) values (3, '49', 'Bogdan Circiumaru');
insert into event_user(event_fk, trackCode, label) values (3, '50', 'Leonard Barbu');
insert into event_user(event_fk, trackCode, label) values (3, '51', 'Till Streichert');
insert into event_user(event_fk, trackCode, label) values (3, '52', 'Mark Miller');
insert into event_user(event_fk, trackCode, label) values (3, '53', 'Andy Brunner');
insert into event_user(event_fk, trackCode, label) values (3, '54', 'Victor Radoi');
insert into event_user(event_fk, trackCode, label) values (2, '201', 'Eduard Albulescu');
insert into event_user(event_fk, trackCode, label) values (2, '202', 'Ana Elena Andrei');
insert into event_user(event_fk, trackCode, label) values (2, '203', 'Catalina Ioana Andrei');
insert into event_user(event_fk, trackCode, label) values (2, '204', 'Lucian Anghelus');
insert into event_user(event_fk, trackCode, label) values (2, '205', 'Andreea Nicoleta Anghelus');
insert into event_user(event_fk, trackCode, label) values (2, '206', 'Ilinca Badea');
insert into event_user(event_fk, trackCode, label) values (2, '207', 'Malin Balasel');
insert into event_user(event_fk, trackCode, label) values (2, '208', 'Cora Baltes');
insert into event_user(event_fk, trackCode, label) values (2, '209', 'Calin Baltes');
insert into event_user(event_fk, trackCode, label) values (2, '210', 'Cristian Banica');
insert into event_user(event_fk, trackCode, label) values (2, '211', 'Andrei Banica');
insert into event_user(event_fk, trackCode, label) values (2, '212', 'Liviu Traian Barbatei');
insert into event_user(event_fk, trackCode, label) values (2, '213', 'Cosmin Batica');
insert into event_user(event_fk, trackCode, label) values (2, '214', 'Romeo Begu');
insert into event_user(event_fk, trackCode, label) values (2, '215', 'Olga Beschea');
insert into event_user(event_fk, trackCode, label) values (2, '216', 'Adrian Blaga');
insert into event_user(event_fk, trackCode, label) values (2, '217', 'Tanase Bogdan Costin');
insert into event_user(event_fk, trackCode, label) values (2, '218', 'Daniel Mircea Bolog');
insert into event_user(event_fk, trackCode, label) values (2, '219', 'Razvan Bucataru');
insert into event_user(event_fk, trackCode, label) values (2, '220', 'Sebastian Cantaragiu');
insert into event_user(event_fk, trackCode, label) values (2, '221', 'Florin Capraru');
insert into event_user(event_fk, trackCode, label) values (2, '222', 'Marius Cimpeanu');
insert into event_user(event_fk, trackCode, label) values (2, '223', 'Laurentiu Gabriel Ciocirlan');
insert into event_user(event_fk, trackCode, label) values (2, '224', 'Alexandru Cîtea');
insert into event_user(event_fk, trackCode, label) values (2, '225', 'Alexandru Constantinescu-Lupsoiu');
insert into event_user(event_fk, trackCode, label) values (2, '226', 'Radu Cordosan');
insert into event_user(event_fk, trackCode, label) values (2, '227', 'Alexandru Craciunescu');
insert into event_user(event_fk, trackCode, label) values (2, '228', 'Andrei Cristescu');
insert into event_user(event_fk, trackCode, label) values (2, '229', 'Catalin Dumitrache');
insert into event_user(event_fk, trackCode, label) values (2, '230', 'Oana-Iulia Dumitrescu');
insert into event_user(event_fk, trackCode, label) values (2, '231', 'Rares Dumitru');
insert into event_user(event_fk, trackCode, label) values (2, '232', 'Alin George Dutescu');
insert into event_user(event_fk, trackCode, label) values (2, '233', 'Gattoni Fabio');
insert into event_user(event_fk, trackCode, label) values (2, '234', 'Neacsu Gabriela');
insert into event_user(event_fk, trackCode, label) values (2, '235', 'Adrian Ganciu');
insert into event_user(event_fk, trackCode, label) values (2, '236', 'Daniel Geanta');
insert into event_user(event_fk, trackCode, label) values (2, '237', 'Bogdan Gheorghe');
insert into event_user(event_fk, trackCode, label) values (2, '238', 'Alexandru Ghiorghies');
insert into event_user(event_fk, trackCode, label) values (2, '239', 'Marius Gusca');
insert into event_user(event_fk, trackCode, label) values (2, '240', 'Mircea Nicolae Harapu');
insert into event_user(event_fk, trackCode, label) values (2, '241', 'Raluca Horvath');
insert into event_user(event_fk, trackCode, label) values (2, '242', 'Catalin Iancovici');
insert into event_user(event_fk, trackCode, label) values (2, '243', 'Bogdan Iftimie');
insert into event_user(event_fk, trackCode, label) values (2, '244', 'Ovidiu Ignat');
insert into event_user(event_fk, trackCode, label) values (2, '245', 'Mihai Ionescu');
insert into event_user(event_fk, trackCode, label) values (2, '246', 'Florin Iosif');
insert into event_user(event_fk, trackCode, label) values (2, '247', 'Raul-Gabriel Irimie');
insert into event_user(event_fk, trackCode, label) values (2, '248', 'Alexandru Isaia');
insert into event_user(event_fk, trackCode, label) values (2, '249', 'Alin Ivancea');
insert into event_user(event_fk, trackCode, label) values (2, '250', 'Mihai Jambore');
insert into event_user(event_fk, trackCode, label) values (2, '251', 'Ovidiu Maracine');
insert into event_user(event_fk, trackCode, label) values (2, '252', 'Alexandru Mares');
insert into event_user(event_fk, trackCode, label) values (2, '253', 'Claudiu Gabriel Marin');
insert into event_user(event_fk, trackCode, label) values (2, '254', 'Bogdan Marinescu');
insert into event_user(event_fk, trackCode, label) values (2, '255', 'Mircea-Ioan Mihai');
insert into event_user(event_fk, trackCode, label) values (2, '256', 'Ana Mirea');
insert into event_user(event_fk, trackCode, label) values (2, '257', 'Vlad Miron');
insert into event_user(event_fk, trackCode, label) values (2, '258', 'Cristian Mocanu');
insert into event_user(event_fk, trackCode, label) values (2, '259', 'Dan Muraru');
insert into event_user(event_fk, trackCode, label) values (2, '260', 'Catalin Muraru');
insert into event_user(event_fk, trackCode, label) values (2, '261', 'Gabriela Neacsu');
insert into event_user(event_fk, trackCode, label) values (2, '262', 'George Nicolae');
insert into event_user(event_fk, trackCode, label) values (2, '263', 'Laurentiu Nicolaescu');
insert into event_user(event_fk, trackCode, label) values (2, '264', 'Paul Bogdan Nicolescu');
insert into event_user(event_fk, trackCode, label) values (2, '265', 'Serban Nisipeanu');
insert into event_user(event_fk, trackCode, label) values (2, '266', 'Valentin Nita');
insert into event_user(event_fk, trackCode, label) values (2, '267', 'Radu Nita');
insert into event_user(event_fk, trackCode, label) values (2, '268', 'Constantin Nitu');
insert into event_user(event_fk, trackCode, label) values (2, '269', 'Andrei-Sorin Nitu');
insert into event_user(event_fk, trackCode, label) values (2, '270', 'Alexandru Ose');
insert into event_user(event_fk, trackCode, label) values (2, '271', 'Bogdan - Mihail Palaghian');
insert into event_user(event_fk, trackCode, label) values (2, '272', 'Cristi Panica');
insert into event_user(event_fk, trackCode, label) values (2, '273', 'Stefan Paun');
insert into event_user(event_fk, trackCode, label) values (2, '274', 'Lucian Paun');
insert into event_user(event_fk, trackCode, label) values (2, '275', 'Mario Pescaru');
insert into event_user(event_fk, trackCode, label) values (2, '276', 'Ion-Gheorghe Petrovai');
insert into event_user(event_fk, trackCode, label) values (2, '277', 'Felix Pirvan');
insert into event_user(event_fk, trackCode, label) values (2, '278', 'Marius Plevan');
insert into event_user(event_fk, trackCode, label) values (2, '279', 'Bogdan Popa');
insert into event_user(event_fk, trackCode, label) values (2, '280', 'Valentin Popescu');
insert into event_user(event_fk, trackCode, label) values (2, '281', 'Cristian Popescu');
insert into event_user(event_fk, trackCode, label) values (2, '282', 'Nastasia Anca Popescu');
insert into event_user(event_fk, trackCode, label) values (2, '283', 'Anca Popescu');
insert into event_user(event_fk, trackCode, label) values (2, '284', 'Adrian Popescu');
insert into event_user(event_fk, trackCode, label) values (2, '285', 'Cosmina Preda');
insert into event_user(event_fk, trackCode, label) values (2, '286', 'Alexandru Pufan');
insert into event_user(event_fk, trackCode, label) values (2, '287', 'Daniela Purcarea');
insert into event_user(event_fk, trackCode, label) values (2, '288', 'Cristian Purcaru');
insert into event_user(event_fk, trackCode, label) values (2, '289', 'Marian Radu');
insert into event_user(event_fk, trackCode, label) values (2, '290', 'Gheorghita Rafaila');
insert into event_user(event_fk, trackCode, label) values (2, '291', 'Stefan Radu Riza');
insert into event_user(event_fk, trackCode, label) values (2, '292', 'Dan Petru Rosu');
insert into event_user(event_fk, trackCode, label) values (2, '293', 'Thomas Royer');
insert into event_user(event_fk, trackCode, label) values (2, '294', 'Daniel Ruse');
insert into event_user(event_fk, trackCode, label) values (2, '295', 'George Constantin Rusu');
insert into event_user(event_fk, trackCode, label) values (2, '296', 'Minodora Savulescu');
insert into event_user(event_fk, trackCode, label) values (2, '297', 'Silviu-Călin Secotă');
insert into event_user(event_fk, trackCode, label) values (2, '298', 'Mihai Serbanescu');
insert into event_user(event_fk, trackCode, label) values (2, '299', 'Aurelian Sideri');
insert into event_user(event_fk, trackCode, label) values (2, '300', 'Daniel Alin Simionescu');
insert into event_user(event_fk, trackCode, label) values (2, '301', 'Mihai Solomon');
insert into event_user(event_fk, trackCode, label) values (2, '302', 'Sebastian Sopon');
insert into event_user(event_fk, trackCode, label) values (2, '303', 'Bogdan Spiridon');
insert into event_user(event_fk, trackCode, label) values (2, '304', 'Alin Stanciu');
insert into event_user(event_fk, trackCode, label) values (2, '305', 'Alexandru Stancu');
insert into event_user(event_fk, trackCode, label) values (2, '306', 'Alexandru Stanculescu');
insert into event_user(event_fk, trackCode, label) values (2, '307', 'Iulian Stanculescu');
insert into event_user(event_fk, trackCode, label) values (2, '308', 'Tudor Stoia');
insert into event_user(event_fk, trackCode, label) values (2, '309', 'Catalin Tamas');
insert into event_user(event_fk, trackCode, label) values (2, '310', 'Eduard Ticu');
insert into event_user(event_fk, trackCode, label) values (2, '311', 'Alin Toma');
insert into event_user(event_fk, trackCode, label) values (2, '312', 'Liviu Tomescu');
insert into event_user(event_fk, trackCode, label) values (2, '313', 'Octavian Trofin');
insert into event_user(event_fk, trackCode, label) values (2, '314', 'Dumiutru-Alexandru Tuta');
insert into event_user(event_fk, trackCode, label) values (2, '315', 'Razvan Ursu');
insert into event_user(event_fk, trackCode, label) values (2, '316', 'Vlad Urzica');
insert into event_user(event_fk, trackCode, label) values (2, '317', 'Georgian Voicu');
insert into event_user(event_fk, trackCode, label) values (2, '318', 'Ovidiu Zagrebelinai');
insert into event_user(event_fk, trackCode, label) values (2, '319', 'Stefan Marius Zgripcea');
insert into event_user(event_fk, trackCode, label) values (2, '320', 'Sorin Zidaru');
insert into event_user(event_fk, trackCode, label) values (2, '321', 'Sergiu Acsinte');
insert into event_user(event_fk, trackCode, label) values (2, '322', 'Cristian Alecsa');
insert into event_user(event_fk, trackCode, label) values (2, '323', 'Adrian Bratucu');
insert into event_user(event_fk, trackCode, label) values (2, '324', 'Cristinel Bulai');
insert into event_user(event_fk, trackCode, label) values (2, '325', 'Simin Calinescu');
insert into event_user(event_fk, trackCode, label) values (2, '326', 'Raul Clinciu');
insert into event_user(event_fk, trackCode, label) values (2, '327', 'Florin Colt');
insert into event_user(event_fk, trackCode, label) values (2, '328', 'Calin Constantinescu');
insert into event_user(event_fk, trackCode, label) values (2, '329', 'Mihai Doncea');
insert into event_user(event_fk, trackCode, label) values (2, '330', 'Ionut Dragan');
insert into event_user(event_fk, trackCode, label) values (2, '331', 'Florin Dragutoiu');
insert into event_user(event_fk, trackCode, label) values (2, '332', 'Ciprian Fibrihi');
insert into event_user(event_fk, trackCode, label) values (2, '333', 'Gheorghe Sorin Flonta');
insert into event_user(event_fk, trackCode, label) values (2, '334', 'Marius Iana');
insert into event_user(event_fk, trackCode, label) values (2, '335', 'ioan bogdan Juncu');
insert into event_user(event_fk, trackCode, label) values (2, '336', 'mihail Juncu');
insert into event_user(event_fk, trackCode, label) values (2, '337', 'Bogdan Laslau');
insert into event_user(event_fk, trackCode, label) values (2, '338', 'Rolland Mereg');
insert into event_user(event_fk, trackCode, label) values (2, '339', 'Alexandru Nestian');
insert into event_user(event_fk, trackCode, label) values (2, '340', 'Denise Omer');
insert into event_user(event_fk, trackCode, label) values (2, '341', 'Alexandru Petrache');
insert into event_user(event_fk, trackCode, label) values (2, '342', 'Cosmin Purcaroiu');
insert into event_user(event_fk, trackCode, label) values (2, '343', 'Florin Daniel Radu');
insert into event_user(event_fk, trackCode, label) values (2, '344', 'Mihail Rusu');
insert into event_user(event_fk, trackCode, label) values (2, '345', 'Sorin Sava');
insert into event_user(event_fk, trackCode, label) values (2, '346', 'Romulus Titus');
insert into event_user(event_fk, trackCode, label) values (2, '347', 'Cosmina Toma');
insert into event_user(event_fk, trackCode, label) values (2, '348', 'Florin Toma');
insert into event_user(event_fk, trackCode, label) values (2, '349', 'Calin Ionut Constantinescu');
insert into event_user(event_fk, trackCode, label) values (2, '350', 'Bogdan Carlos Apostol');
insert into event_user(event_fk, trackCode, label) values (2, '351', 'Stefan Nefedov');
insert into event_user(event_fk, trackCode, label) values (2, '352', 'Vlad Posea');
insert into event_user(event_fk, trackCode, label) values (2, '353', 'Emil Slusanschi');
insert into event_user(event_fk, trackCode, label) values (2, '354', 'Georgiana Radoi');
insert into event_user(event_fk, trackCode, label) values (2, '355', 'Catalina  Andrei');
insert into event_user(event_fk, trackCode, label) values (2, '356', 'Dragos Jula');
insert into event_user(event_fk, trackCode, label) values (2, '357', 'Iuliana Apostol');
insert into event_user(event_fk, trackCode, label) values (2, '358', 'Georgian Tudor');
insert into event_user(event_fk, trackCode, label) values (2, '359', 'Florin Capraru');
insert into event_user(event_fk, trackCode, label) values (2, '360', 'Cosmin Batica');
